### ISSUE TITLE
Editing conkyrc

### ISSUE THREAD

**Issue by nicolasmaia** [takattila/Clock-With-Weather-Conky#1]
Is it possible to edit the config manually? By changing the conkyrc, for example. Except I can't find a conkyrc in this case.

**Comment by takattila** [comment]
Hi nicolasmaia,
thank you for your question and sorry for the late reply!

Yes you can edit the "conkyrc" file of course, but in this case the "conkyrc" is renamed to "[app.cfg](https://github.com/takattila/Clock-With-Weather-Conky/blob/master/app.cfg)", which you can find on the root of this project.
