### ISSUE TITLE
Conky covering the window on i3-wm

### ISSUE THREAD

**Issue by fuu38** [takattila/Clock-With-Weather-Conky#2]
I am using this conky with i3-wm on Manjaro.
Yes, this conky is really cool, but in my environment,it has a problem.
Please look at attached picture.As indicated in the title, conky window covering on other window.

To fix this problem,I changed "app.cfg" like below.
```
-own_window_type = "normal"
+own_window_type = "override"
```

I used machine translation and this is my first issue with english,so I am sorry for the hard-to-read English.
Thanks.
![image](https://user-images.githubusercontent.com/49513840/124420822-2546d300-dd9b-11eb-8d3d-826487bf3016.png)

**Comment by takattila** [comment]
Thank you for your suggestion!

This repo is not yet ready to support "i3" Window Manager, but as I see it, you have found a solution to the alignment problem.

Of course, you can modify the configuration files locally at any time, but if you have any ideas for automation, please feel free to open a PR with your suggestion or modification!
